# Generated by Django 5.2.7 on 2025-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'no puede estar en blanco', 'max_length': 'maximo numero de caracteres 30', 'unique': 'Este nombre ya esta registrado'}, max_length=30, unique=True)),
                ('age', models.CharField(error_messages={'black': 'No puede estar en blanco', 'max_length': 'No puede tener mas de 2 digitos'}, max_length=2)),
                ('yearstudent', models.CharField(error_messages={'blank': 'No puede estar en Blanco', 'max_length': 'No puede Tener mas de 5 caracteres'}, max_length=5)),
                ('dni', models.CharField(blank=True, error_messages={'blank': 'Puede estar en blanco', 'max_length': 'No puede tener mas de 20 caracteres', 'unique': 'Esta Cedula ya esta registrada, Verifique los Datos Ingresados'}, max_length=20, unique=True)),
                ('family', models.CharField(error_messages={'blank': 'No puede Estar en Blanco', 'max_length': 'No puede tener mas de 100 caracteres'}, max_length=100)),
                ('phone', models.IntegerField(error_messages={'blank': 'No puede estar en Blanco el numero de Telefono', 'max_length': 'No puede Tener mas de 40 caracteres'}, max_length=40)),
                ('note', models.CharField(blank=True)),
            ],
        ),
    ]
