# Generated by Django 5.2.7 on 2025-11-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'no puede estar en blanco', 'max_length': 'maximo numero de caracteres 30', 'unique': 'Este nombre ya esta registrado'}, max_length=30, unique=True)),
                ('age', models.IntegerField(error_messages={'black': 'No puede estar en blanco', 'max_length': 'No puede tener mas de 2 digitos'}, max_length=2)),
                ('yearstudent', models.CharField(error_messages={'blank': 'No puede estar en Blanco', 'max_length': 'No puede Tener mas de 5 caracteres'}, max_length=5)),
                ('dni', models.CharField(blank=True, error_messages={'blank': 'Puede estar en blanco', 'max_length': 'No puede tener mas de 20 caracteres', 'unique': 'Esta Cedula ya esta registrada, Verifique los Datos Ingresados'}, max_length=20, unique=True)),
                ('family', models.CharField(error_messages={'blank': 'No puede Estar en Blanco', 'max_length': 'No puede tener mas de 100 caracteres'}, max_length=100)),
                ('phone', models.CharField(error_messages={'blank': 'No puede estar en Blanco el numero de Telefono', 'max_length': 'No puede Tener mas de 40 caracteres'}, max_length=40)),
                ('note', models.CharField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachersdata',
            name='family',
        ),
        migrations.RemoveField(
            model_name='teachersdata',
            name='yearstudent',
        ),
        migrations.AddField(
            model_name='teachersdata',
            name='yearstudentasign',
            field=models.CharField(error_messages={'blank': 'No puede estar en blanco', 'max_length': 'no puede tener mas de 10'}, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teachersdata',
            name='age',
            field=models.IntegerField(error_messages={'blank': 'no pueden estar en blanco', 'max_length': 'no se pueden mas de 2 caracteres'}, max_length=2),
        ),
        migrations.AlterField(
            model_name='teachersdata',
            name='dni',
            field=models.CharField(error_messages={'blank': 'No Puede estar en blanco', 'max_length': 'No puede tener mas de 20 caracteres', 'unique': 'Esta Cedula ya esta registrada, Verifique los Datos Ingresados'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teachersdata',
            name='name',
            field=models.CharField(error_messages={'blank': 'no se puede dejar en blanco', 'max_length': 'No se puede tener mas de 40 caracteres'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='teachersdata',
            name='note',
            field=models.CharField(blank=True, error_messages={'max_length': 'no pude contener mas de 255 caracteres'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='teachersdata',
            name='phone',
            field=models.CharField(error_messages={'blank': 'No puede estar en Blanco el numero de Telefono', 'max_length': 'No puede Tener mas de 40 caracteres'}, max_length=40),
        ),
    ]
