# Generated by Django 5.2.7 on 2025-11-17 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentsdata_remove_teachersdata_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='age',
            field=models.IntegerField(error_messages={'black': 'No puede estar en blanco'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='teachersdata',
            name='age',
            field=models.IntegerField(error_messages={'blank': 'no pueden estar en blanco'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
