# Generated by Django 5.2.7 on 2025-11-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studentsdata_age_alter_teachersdata_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'blank': 'No puede estar en blanco', 'max_length': 'No se puede tener mas de 50 caracteres'}, max_length=50)),
                ('email', models.CharField(error_messages={'blank': 'No puede estar en Blanco', 'max_length': 'No puede Tener mas de 70 caracteres'}, max_length=70)),
                ('password', models.CharField(error_messages={'blank': 'No puede estar en blanco', 'max_length': 'No puede tener mas de 25 caracteres'}, max_length=25)),
            ],
        ),
    ]
