# Generated by Django 5.2.7 on 2025-11-27 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(error_messages={'blank': 'No puede estar en blanco', 'max_length': 'No puede tener mas de 70 caracteres', 'unique': 'Este email ya está en uso.'}, max_length=70, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un email válido')]),
        ),
    ]
