# Generated by Django 5.2.7 on 2025-11-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(error_messages={'blank': 'No puede estar en Blanco', 'max_length': 'No puede Tener mas de 70 caracteres'}, max_length=70),
        ),
    ]
